# Generated by Django 4.2.3 on 2023-07-26 02:21

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_ativos_cargo_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'engrenagem'), ('lni-stats-up', 'gráfico'), ('lni-user', 'usuário'), ('lni-layers', 'design'), ('lni-mobile', 'celular'), ('lni-rocket', 'foguete')], max_length=12, verbose_name='Ícone'),
        ),
    ]
