# Generated by Django 4.2.3 on 2023-07-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_precos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Precos',
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Preço', 'verbose_name_plural': 'Preços'},
        ),
    ]
